version: '2'
services:
  dunna-app:
    image: dunna
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATASOURCE_URL=jdbc:mysql://dunna-mysql:3306/dunna?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
      - JHIPSTER_SLEEP=30 # gives time for other services to boot before the application
      - SPRING_DATA_JEST_URI=http://dunna-elasticsearch:9200
      - SPRING_ELASTICSEARCH_REST_URIS=http://dunna-elasticsearch:9200
    ports:
      - 8080:8080
  dunna-mysql:
    extends:
      file: mysql.yml
      service: dunna-mysql
  dunna-elasticsearch:
    extends:
      file: elasticsearch.yml
      service: dunna-elasticsearch
